### ISSUE TITLE
1. Virtualisation XML config

### ISSUE THREAD

**Issue by isacandrei** [joomla-projects/gsoc17_parallel_testing#7]
Configure the xml needed by the virtualisation repo so that it will create the desired testing environment.

**Comment by nibra** [comment]
Could you please elaborate this a bit more?

**Comment by isacandrei** [comment]
Sure. So the idea is that we need the following containers in the testing environment:
1. All the combinations between the needed php versions(5.4->7.1) and Joomla versions(3.7 - current version, 3.8 - next version and stating) running on apache. 
2. A number of selenium testing containers that can be configurable.

I am currently testing if how the virtualisation repo handles the Joomla containers and as mentioned before I have encountered some issued that I have managed to solve so far.(https://github.com/isacandrei/virtualisation/commit/3ee260e589b5fc5873924e07f749085ec8daf120 )

The next step would be to define exactly how the Selenium containers would work and manually test if they can perform the tests on a given Joomla server.
